<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.GenAI" Version="0.10.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.2.0" />
    <PackageReference Include="Microsoft.Identity.Client" Version="4.81.0" />
    <PackageReference Include="Microsoft.PowerBI.Api" Version="5.0.0" />
    <PackageReference Include="Microsoft.Rest.ClientRuntime" Version="2.3.24" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Data\Data.csproj" />
    <ProjectReference Include="..\DbModels\DbModels.csproj" />
    <ProjectReference Include="..\School_IServices\School_IServices.csproj" />
    <ProjectReference Include="..\School_View_Models\School_View_Models.csproj" />
  </ItemGroup>

</Project>
